name: "Test Features"
on: 
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
          matrix:
            features: [ "go", "dotnet", "go dotnet"  ]
            baseImage: [ "ubuntu:focal" ]
    steps:
      - uses: actions/checkout@v2

      - name: " Testing '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: npx --yes ./dev-containers-cli-0.3.0.tgz features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} -c `pwd` 
